import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { 
  Sparkles, 
  TrendingUp, 
  AlertTriangle, 
  Zap, 
  Star, 
  Activity, 
  ArrowRight,
  RefreshCw,
  Lightbulb,
  BrainCircuit,
  BarChart3
} from 'lucide-react';

const AIInsights = () => {
  const [insights, setInsights] = useState([]);
  const [stats, setStats] = useState({
    velocity: '12.4%',
    active_predictions: '842',
    confidence: '98.4%',
    latency: '14ms',
    event_rate: '4.2k',
    node_count: '18'
  });
  const [loading, setLoading] = useState(true);

  const API_BASE = 'http://localhost:8003/api/v1';

  const fetchData = async () => {
    try {
      setLoading(true);
      const res = await axios.get(`${API_BASE}/admin/ai-insights`);
      if (res.data.success) {
        setInsights(res.data.insights);
        if (res.data.stats) {
          setStats(res.data.stats);
        }
      }
    } catch (err) {
      console.error(`Failed to fetch AI insights:`, err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  const getImpactColor = (impact) => {
    const i = impact.toLowerCase();
    if (i === 'high') return 'text-red-500 bg-red-50';
    if (i === 'medium') return 'text-orange-500 bg-orange-50';
    if (i === 'growth') return 'text-emerald-500 bg-emerald-50';
    return 'text-blue-500 bg-blue-50';
  };

  const getIcon = (name) => {
    switch (name) {
      case 'TrendingUp': return <TrendingUp size={20} />;
      case 'AlertTriangle': return <AlertTriangle size={20} />;
      case 'Zap': return <Zap size={20} />;
      case 'Star': return <Star size={20} />;
      case 'Activity': return <Activity size={20} />;
      default: return <Sparkles size={20} />;
    }
  };

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-1000">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div>
          <h1 className="text-3xl font-black text-slate-900 tracking-tight flex items-center gap-3">
             <div className="p-2 rounded-xl bg-purple-50 text-purple-600 border border-purple-100 shadow-sm">
                <BrainCircuit size={24} />
             </div>
             AI Operational Intelligence
          </h1>
          <p className="text-slate-500 font-medium mt-1">Real-time platform insights generated by neural analysis of marketplace trends.</p>
        </div>
        <button 
           onClick={fetchData}
           className="bg-white border border-slate-200 text-slate-700 px-6 py-2.5 rounded-xl text-xs font-black shadow-sm hover:bg-slate-50 flex items-center gap-2 transition-all active:scale-95"
        >
           <RefreshCw size={16} className={loading ? 'animate-spin' : ''} /> Regenerate Insights
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
         <div className="bg-slate-900 rounded-[32px] p-6 text-white relative overflow-hidden group col-span-1 md:col-span-2">
            <div className="absolute top-0 right-0 p-8 opacity-10 group-hover:scale-110 transition-transform duration-700">
               <Activity size={100} />
            </div>
            <div className="relative z-10 space-y-4">
               <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/10 backdrop-blur-md text-[10px] font-black uppercase tracking-widest text-purple-300 border border-white/5">
                  <Sparkles size={12} /> Live Engine
               </div>
               <h2 className="text-2xl font-black tracking-tight">System Pulse: <span className="text-purple-400 italic font-medium">Stable</span></h2>
               <p className="text-slate-400 text-sm font-medium leading-relaxed max-w-sm">Neural network is currently processing {stats.event_rate} events/sec across {stats.node_count} regional nodes.</p>
               <div className="flex items-center gap-6 pt-4 border-t border-white/5">
                   <div>
                    <p className="text-[10px] font-black uppercase text-slate-500 tracking-tighter">Confidence</p>
                    <p className="text-lg font-black text-emerald-400 font-mono italic">{stats.confidence}</p>
                  </div>
                  <div>
                    <p className="text-[10px] font-black uppercase text-slate-500 tracking-tighter">Latency</p>
                    <p className="text-lg font-black text-blue-400 font-mono italic">{stats.latency}</p>
                  </div>
               </div>
            </div>
         </div>
         <div className="bg-white rounded-[32px] p-8 border border-slate-100 flex flex-col justify-between shadow-sm shadow-slate-200/50">
           <div className="p-3 bg-blue-50 text-blue-600 rounded-2xl w-fit"><BarChart3 size={24} /></div>
           <div className="mt-6">
             <p className="text-3xl font-black text-slate-900 tracking-tighter">
               {stats.velocity} 
               <span className={`text-sm ml-1 ${parseFloat(stats.velocity) >= 0 ? 'text-emerald-500' : 'text-red-500'}`}>
                 {parseFloat(stats.velocity) >= 0 ? '↑' : '↓'}
               </span>
             </p>
             <p className="text-xs font-bold text-slate-400 mt-1 uppercase tracking-widest">Growth Velocity</p>
           </div>
         </div>
         <div className="bg-white rounded-[32px] p-8 border border-slate-100 flex flex-col justify-between shadow-sm shadow-slate-200/50">
           <div className="p-3 bg-orange-50 text-orange-600 rounded-2xl w-fit"><Lightbulb size={24} /></div>
           <div className="mt-6">
             <p className="text-3xl font-black text-slate-900 tracking-tighter">{stats.active_predictions}</p>
             <p className="text-xs font-bold text-slate-400 mt-1 uppercase tracking-widest">Active Predictions</p>
           </div>
         </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
         {loading ? (
            Array(4).fill(0).map((_, i) => <div key={i} className="animate-pulse bg-slate-100 h-48 rounded-[40px]"></div>)
         ) : insights.map((insight) => (
            <div key={insight.id} className="bg-white p-8 rounded-[40px] border border-slate-100 shadow-sm hover:shadow-xl hover:shadow-slate-200/50 transition-all group relative overflow-hidden">
               <div className={`absolute top-0 right-0 w-24 h-24 translate-x-12 -translate-y-12 rounded-full opacity-5 group-hover:scale-150 transition-transform duration-1000 ${getImpactColor(insight.impact).split(' ')[1]}`} />
               <div className="flex flex-col h-full relative z-10">
                  <div className="flex items-center justify-between mb-6">
                     <span className={`px-4 py-1.5 rounded-full text-[10px] font-black uppercase tracking-widest ${getImpactColor(insight.impact)}`}>
                        {insight.impact} IMPACT
                     </span>
                     <span className="text-[10px] font-black text-slate-300 uppercase tracking-widest italic">{insight.type}</span>
                  </div>
                  <div className="flex items-start gap-4 flex-1">
                     <div className="w-14 h-14 bg-slate-50 text-slate-900 flex items-center justify-center rounded-2xl group-hover:bg-slate-900 group-hover:text-white transition-all duration-500 shadow-sm border border-slate-100">
                        {getIcon(insight.icon)}
                     </div>
                     <div className="flex-1">
                        <h3 className="text-xl font-black text-slate-900 leading-tight mb-2 group-hover:text-purple-600 transition-colors">{insight.title}</h3>
                        <p className="text-sm font-medium text-slate-500 leading-relaxed">{insight.description}</p>
                     </div>
                  </div>
                  <div className="mt-8 pt-6 border-t border-slate-50 flex items-center justify-between opacity-40 group-hover:opacity-100 transition-opacity">
                     <button className="text-[10px] font-black uppercase tracking-widest text-slate-900 flex items-center gap-2 hover:gap-3 transition-all">
                        Execute Suggested Optimization <ArrowRight size={14} />
                     </button>
                  </div>
               </div>
            </div>
         ))}
      </div>
    </div>
  );
};

export default AIInsights;
